language: ruby
bundler_args: "--without production --path vendor/bundle"
rvm:
- 2.3.0
gemfile:
- Gemfile
cache: bundler
services:
- mysql
branches:
  only:
  - master
script:
- bundle exec rubocop app
- bundle exec rubocop lib
- bundle exec rubocop spec
- bundle exec rake test
before_install: gem update bundler
before_script:
- export DISPLAY=:99.0
- export RAILS_ENV=test
- sh -e /etc/init.d/xvfb start
- cp config/database.travis.yml config/database.yml
- mysql -e "create database famiphotos_test;" 
- mysql -e "create database famiphotos_master_test;" 
- bundle exec rake db:migrate
after_failure:
- bundle exec rake --version
notifications:
  slack: s-nakamura:70ZBpyKjrkR5Ps3lKy4wLjUu
