language: ruby
bundler_args: "--without production --path vendor/bundle"
rvm:
- 2.1.5
gemfile:
- Gemfile
env:
- DB=mysql
branches:
  only:
  - master
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rubocop app
- bundle exec rubocop lib
- bundle exec rubocop spec
before_install: gem update bundler
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- cp config/database.travis.yml config/database.yml
- mysql -e 'create database famiphotos_test'
after_failure:
- bundle exec rake --version
deploy:
  provider: heroku
  api_key:
    secure: 3433e2807ccbf3e51e0cd78029462d8b99ed3902
  app: daphy
  on:
    repo: nakaearth/famiphotos
notifications:
  slack: s-nakamura:70ZBpyKjrkR5Ps3lKy4wLjUu
