version: "3"
services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    env_file:
      - ./environments/db.env
    volumes:
      - db_data:/var/lib/mysql
      - ./containers/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - esnet

  es01:
    build:
      context: docker_image/elasticsearch
    container_name: es01
    hostname: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    networks:
      - esnet

  es02:
    build:
      context: docker_image/elasticsearch
    container_name: es02
    hostname: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - 9201:9201
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - esnet

  headPlugin:
    image: 'mobz/elasticsearch-head:5'
    container_name: head
    ports:
      - '9100:9100'
    networks:
      - esnet
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./environments/app.env
    volumes:
      - bundle_install:/famiphotos/vendor/bundle
      - ./app:/famiphotos/app
      - ./bin:/famiphotos/bin
      - ./config:/famiphotos/config
      - ./config.ru:/famiphotos/config.ru
      - ./db:/famiphotos/db
      - ./.rubocop.yml:/famiphotos/.rubocop.yml
      - ./Gemfile:/famiphotos/Gemfile
      - ./Gemfile.lock:/famiphotos/Gemfile.lock
      - ./lib:/famiphotos/lib
      - ./public:/famiphotos/public
      - ./Rakefile:/famiphotos/Rakefile
      - ./spec:/famiphotos/spec
      - ./log:/famiphotos/log
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    links:
      - db
      - es01
      - es02
    ports:
      - "3000:3000"
      - "5000:5000"
    stdin_open: true
    tty: true
    networks:
      - esnet

volumes:
  db_data:
    driver: local
  esdata01:
    driver: local
  esdata02:
    driver: local
  bundle_install:

networks:
  esnet:
