defaults: &defaults
  adapter: mysql2
  username: root
  password:
  database: famiphotos_<%= ENV['RAILS_ENV'] %>
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
