default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  pool: 5
  reconnect: false
  host: <%= ENV['DB_SERVERNAME'] %>
  username: <%= ENV.fetch('DB_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DB_PASSWORD') { '' } %>
  strict: false

development:
  <<: *default
  database: famiphotos_development

test:
  <<: *default
  database: famiphotos_test

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_SERVERNAME'] %>
